apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-engine
  template:
    metadata:
      labels:
        app: ad-engine
    spec:
      containers:
      - name: engine
        image: jorgemorenooz/ad_engine:latest
        ports:
        - containerPort: 8081    # socket for drones
        - containerPort: 5002    # HTTPS API
        volumeMounts:
        - name: cert-volume
          mountPath: /app/cert
        - name: figuras-volume
          mountPath: /app/figures.json
          subPath: figures.json
        - name: ciudades-volume
          mountPath: /app/ciudades.json
          subPath: ciudades.json
        - name: credentials-volume
          mountPath: /app/drone_data
      volumes:
      - name: cert-volume
        secret:
          secretName: ad-engine-certs
      - name: figuras-volume
        configMap:
          name: figuras-config
      - name: ciudades-volume
        configMap:
          name: ciudades-config
      - name: credentials-volume
        persistentVolumeClaim:
          claimName: shared-drone-db
