apiVersion: v1
kind: Service
metadata:
  name: ad-engine
spec:
  selector:
    app: ad-engine
  type: NodePort
  ports:
  - name: https
    port: 5002
    targetPort: 5002
    nodePort: 30503
  - name: socket
    port: 8081
    targetPort: 8081
    nodePort: 30504
